## Pass requests that don't refer directly to files in the filesystem to index.php
location / {
    try_files $uri $uri/ /index.php?$query_string;
}

## Pass the PHP scripts to FastCGI server
location ~ \.php$ {
    fastcgi_pass 127.0.0.1:9000;
    fastcgi_index index.php;
    include fastcgi_params;

    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param DOCUMENT_ROOT $document_root;
}

## Whitelist
location ~ ^/favicon\.ico { try_files $uri /index.php; }
location ~ ^/sitemap\.xml { try_files $uri /index.php; }

## Block all .dotfiles except well-known
location ~ /\.(?!well-known).* { deny all; }

## Static file handling
location ~ ^/media { try_files $uri 404; }
location ~ ^/themes/.*/assets { try_files $uri 404; }
